     - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'docs'
          destination-username: 'RootCNC'
          destination-repository: 'RootCNC/Wiki'
          destination-directory: 'Root-2'
          commit-email: 'rcnc3d@gmail.com'